// ===========================================================================
// words.js — bundled word list (static asset).
// An original set of common, concrete English nouns. Not copied from any
// commercial card deck. 25 distinct words are drawn at random per game.
// Stored lowercase; the UI renders them uppercase via CSS.
//
// House rules for adding words, so the deck stays playable:
//  - sorted, unique, lowercase a-z only (no spaces, hyphens or proper nouns);
//  - max 10 characters, because a card has to fit its word on one line and the
//    type shrinks to do it — 10 is already the floor on a narrow phone;
//  - avoid words that contain another word on the list ('hand'/'handle') or sit
//    one letter from one ('watch'/'witch'). Both make clues ambiguous in a way
//    that is nobody's fault and no fun.
// ===========================================================================

export const WORD_LIST = [
  'abbey', 'accordion', 'acorn', 'actor', 'airport', 'alarm', 'alley', 'alligator',
  'almond', 'amber', 'ambulance', 'anchor', 'angel', 'ankle', 'antelope', 'antenna',
  'anvil', 'apple', 'apricot', 'apron', 'arch', 'arena', 'arrow', 'artist',
  'ash', 'astronaut', 'attic', 'aurora', 'author', 'autumn', 'avalanche', 'axe',
  'backpack', 'bacon', 'badge', 'bagel', 'bakery', 'ball', 'ballerina', 'balloon',
  'bamboo', 'banana', 'bandage', 'bandit', 'banjo', 'banker', 'banner', 'barber',
  'barge', 'bark', 'barn', 'barrel', 'basil', 'basin', 'basket', 'bass',
  'bat', 'battery', 'beach', 'beacon', 'beaker', 'bean', 'bear', 'beard',
  'beaver', 'bed', 'bee', 'beetle', 'bell', 'belt', 'bench', 'beret',
  'berry', 'bicycle', 'biscuit', 'bishop', 'bison', 'blade', 'blanket', 'blazer',
  'blender', 'blimp', 'blizzard', 'block', 'blossom', 'blouse', 'board', 'boat',
  'bolt', 'bone', 'bonfire', 'bonnet', 'book', 'boot', 'bottle', 'boulder',
  'bow', 'bowl', 'box', 'bracelet', 'brain', 'branch', 'bread', 'breeze',
  'brick', 'bride', 'bridge', 'brisket', 'broccoli', 'brooch', 'broom', 'brownie',
  'brush', 'bubble', 'bucket', 'buckle', 'bud', 'buffalo', 'bugle', 'bulb',
  'bull', 'bungalow', 'bunker', 'buoy', 'bus', 'butter', 'button', 'cabin',
  'cabinet', 'cable', 'cactus', 'cage', 'cake', 'calendar', 'camel', 'camera',
  'canal', 'candle', 'candy', 'canister', 'canoe', 'canvas', 'canyon', 'cape',
  'captain', 'carafe', 'caramel', 'caravan', 'card', 'cargo', 'carpenter', 'carpet',
  'carriage', 'carrot', 'cart', 'castle', 'cat', 'cathedral', 'cauldron', 'cave',
  'cavern', 'celery', 'cello', 'cereal', 'chain', 'chair', 'chalet', 'chalk',
  'chapel', 'chariot', 'cheek', 'cheese', 'chef', 'cherry', 'chess', 'chicken',
  'chickpea', 'chili', 'chimney', 'chip', 'chisel', 'chocolate', 'choir', 'chord',
  'cilantro', 'cinnamon', 'circle', 'circus', 'citadel', 'city', 'clamp', 'clarinet',
  'cleats', 'cliff', 'cloak', 'clock', 'closet', 'cloud', 'clover', 'clown',
  'coach', 'coast', 'coat', 'cobbler', 'cobra', 'coconut', 'cocoon', 'coil',
  'coin', 'colander', 'collar', 'comb', 'comet', 'compass', 'computer', 'cone',
  'convoy', 'cookie', 'copper', 'coral', 'cork', 'corn', 'costume', 'cottage',
  'cotton', 'couch', 'cougar', 'cow', 'coyote', 'crab', 'cracker', 'cradle',
  'crane', 'crater', 'crayon', 'cream', 'cricket', 'crown', 'crutch', 'crystal',
  'cube', 'cucumber', 'cup', 'curry', 'curtain', 'cushion', 'cyclone', 'cymbal',
  'dagger', 'daisy', 'dam', 'dancer', 'dart', 'dawn', 'decanter', 'deer',
  'denim', 'dentist', 'desert', 'desk', 'detective', 'dew', 'diamond', 'dice',
  'diner', 'dinghy', 'dinosaur', 'discus', 'dock', 'doctor', 'dolphin', 'domino',
  'donkey', 'door', 'dove', 'dragon', 'drawer', 'dress', 'drill', 'drizzle',
  'drone', 'drum', 'duck', 'dugout', 'duke', 'dune', 'dungeon', 'dusk',
  'eagle', 'ear', 'earth', 'easel', 'eel', 'egg', 'elbow', 'elephant',
  'elevator', 'elf', 'elk', 'ember', 'emperor', 'engine', 'engineer', 'envelope',
  'eraser', 'escalator', 'explorer', 'factory', 'falcon', 'fan', 'fang', 'farm',
  'faucet', 'feather', 'fedora', 'fence', 'fern', 'ferry', 'fiddle', 'field',
  'fig', 'finch', 'finger', 'fire', 'fish', 'fjord', 'flag', 'flame',
  'flamingo', 'flask', 'fleet', 'flood', 'flour', 'flower', 'flute', 'fog',
  'folder', 'forest', 'fork', 'fort', 'fossil', 'fountain', 'fox', 'frame',
  'freckle', 'frog', 'frost', 'funnel', 'furnace', 'galaxy', 'garage', 'garden',
  'garlic', 'gate', 'gazelle', 'gear', 'gecko', 'gelato', 'genie', 'geyser',
  'ghost', 'giant', 'ginger', 'giraffe', 'glacier', 'gladiator', 'glass', 'glove',
  'glue', 'goalie', 'goat', 'goblin', 'goggles', 'gold', 'gondola', 'goose',
  'gorge', 'gorilla', 'gown', 'granola', 'grape', 'grass', 'grater', 'grave',
  'gravel', 'grill', 'guard', 'guitar', 'gull', 'gym', 'hail', 'hallway',
  'hammer', 'hammock', 'hamster', 'hand', 'hanger', 'harbor', 'harmonica', 'harness',
  'harp', 'hat', 'hawk', 'hay', 'heart', 'heater', 'hedge', 'heel',
  'helmet', 'hen', 'hermit', 'heron', 'highway', 'hill', 'hinge', 'hippo',
  'hive', 'honey', 'hoof', 'hook', 'horn', 'horse', 'hose', 'hospital',
  'hotel', 'hound', 'house', 'hunter', 'hurdle', 'hurricane', 'hut', 'hyena',
  'iceberg', 'icicle', 'igloo', 'iguana', 'ink', 'iron', 'island', 'ivory',
  'jacket', 'jaguar', 'jar', 'javelin', 'jaw', 'jeans', 'jeep', 'jelly',
  'jersey', 'jester', 'jet', 'jewel', 'judge', 'jug', 'jungle', 'kangaroo',
  'kayak', 'ketchup', 'kettle', 'key', 'kilt', 'kingdom', 'kitchen', 'kite',
  'kitten', 'knee', 'knife', 'knight', 'knot', 'koala', 'label', 'lace',
  'ladder', 'ladle', 'lagoon', 'lake', 'lamp', 'lance', 'lantern', 'laptop',
  'laser', 'lava', 'lawyer', 'leaf', 'leather', 'leg', 'lemon', 'lemur',
  'lens', 'lentil', 'leopard', 'letter', 'lettuce', 'lever', 'library', 'lighthouse',
  'lily', 'lime', 'lion', 'lizard', 'llama', 'lobby', 'lobster', 'lock',
  'lodge', 'log', 'lotus', 'luggage', 'lung', 'lynx', 'magician', 'magnet',
  'magpie', 'mallet', 'mammoth', 'mandolin', 'mango', 'mansion', 'map', 'maple',
  'marble', 'market', 'marsh', 'mask', 'mast', 'mattress', 'mayor', 'maze',
  'meadow', 'mechanic', 'medal', 'melon', 'merchant', 'mermaid', 'meteor', 'microscope',
  'milk', 'mill', 'mine', 'mint', 'mirror', 'mist', 'mitten', 'moat',
  'moccasin', 'mole', 'mongoose', 'monitor', 'monk', 'monkey', 'monsoon', 'moon',
  'moose', 'mop', 'mosque', 'mosquito', 'moss', 'moth', 'mountain', 'mouse',
  'muffin', 'mug', 'mule', 'museum', 'mushroom', 'mustard', 'nail', 'napkin',
  'narwhal', 'necktie', 'needle', 'nest', 'net', 'newt', 'nomad', 'noodle',
  'nose', 'note', 'nurse', 'oak', 'oar', 'oasis', 'oatmeal', 'ocean',
  'octopus', 'olive', 'omelet', 'onion', 'opera', 'orbit', 'orchard', 'oregano',
  'organ', 'ostrich', 'otter', 'ottoman', 'oven', 'overalls', 'owl', 'ox',
  'oyster', 'paddle', 'painter', 'pajamas', 'palace', 'palm', 'panda', 'pansy',
  'panther', 'pants', 'paper', 'paprika', 'parachute', 'parka', 'parrot', 'parsley',
  'pasta', 'pasture', 'paw', 'pawn', 'peach', 'peacock', 'peanut', 'pear',
  'pearl', 'pebble', 'pedal', 'pelican', 'pencil', 'penguin', 'pepper', 'periscope',
  'pharaoh', 'phone', 'piano', 'pickle', 'pier', 'pigeon', 'pillar', 'pillow',
  'pilot', 'pine', 'pipe', 'pirate', 'pistol', 'pitcher', 'pizza', 'planet',
  'plank', 'plate', 'plaza', 'pliers', 'plug', 'plum', 'pocket', 'podium',
  'pollen', 'poncho', 'pond', 'pony', 'porch', 'possum', 'potato', 'pottery',
  'prairie', 'pretzel', 'priest', 'prince', 'printer', 'prism', 'prison', 'pudding',
  'puddle', 'puffin', 'pulley', 'pump', 'pumpkin', 'puppet', 'puppy', 'purse',
  'puzzle', 'pyramid', 'python', 'quail', 'quartz', 'queen', 'quill', 'quilt',
  'quinoa', 'rabbit', 'raccoon', 'racket', 'racquet', 'radar', 'radish', 'raft',
  'rail', 'rain', 'rake', 'ram', 'ranch', 'ranger', 'ratchet', 'raven',
  'razor', 'reef', 'referee', 'reindeer', 'relish', 'rhino', 'ribbon', 'rice',
  'rickshaw', 'ridge', 'ring', 'ripple', 'river', 'road', 'robe', 'robin',
  'robot', 'rocket', 'rooster', 'root', 'rope', 'rose', 'router', 'ruby',
  'rudder', 'rug', 'ruins', 'ruler', 'sable', 'saddle', 'saffron', 'sail',
  'salmon', 'salt', 'samurai', 'sand', 'sandal', 'sapphire', 'sardine', 'satellite',
  'saucer', 'sausage', 'savanna', 'saw', 'saxophone', 'scale', 'scallop', 'scarf',
  'school', 'schooner', 'scientist', 'scissors', 'scooter', 'scorpion', 'screw', 'seal',
  'seaweed', 'sedan', 'seed', 'shadow', 'shampoo', 'shark', 'shawl', 'shed',
  'sheep', 'shell', 'shepherd', 'sheriff', 'shield', 'ship', 'shirt', 'shoe',
  'shorts', 'shoulder', 'shovel', 'shower', 'shrimp', 'sidewalk', 'sieve', 'silk',
  'silo', 'silver', 'sink', 'skate', 'skillet', 'skirt', 'skull', 'skunk',
  'sky', 'sled', 'sleeve', 'slipper', 'sloth', 'smoke', 'snail', 'snake',
  'sneaker', 'snow', 'soap', 'sock', 'sofa', 'soil', 'soldier', 'sorbet',
  'spade', 'spark', 'sparrow', 'spatula', 'spear', 'spider', 'spike', 'spinach',
  'sponge', 'spoon', 'spring', 'sprout', 'spruce', 'square', 'squid', 'squirrel',
  'stable', 'stadium', 'stage', 'stairs', 'stallion', 'stamp', 'stapler', 'star',
  'statue', 'steam', 'steel', 'steeple', 'stem', 'stick', 'stone', 'stool',
  'storm', 'stove', 'straw', 'stream', 'street', 'string', 'studio', 'submarine',
  'sugar', 'suitcase', 'summit', 'sun', 'surgeon', 'swallow', 'swamp', 'swan',
  'sweater', 'switch', 'sword', 'syringe', 'syrup', 'table', 'taco', 'tadpole',
  'tail', 'tank', 'tavern', 'taxi', 'teacher', 'teapot', 'telescope', 'temple',
  'tent', 'termite', 'theater', 'thermos', 'thicket', 'thief', 'thimble', 'thorn',
  'thread', 'throne', 'thumb', 'thunder', 'tiara', 'tide', 'tiger', 'tile',
  'timber', 'toast', 'toboggan', 'tofu', 'tomato', 'tomb', 'tongue', 'tooth',
  'torch', 'tornado', 'toucan', 'tower', 'town', 'track', 'tractor', 'train',
  'trap', 'tray', 'treasure', 'tree', 'triangle', 'trombone', 'trophy', 'trousers',
  'trout', 'trowel', 'truck', 'truffle', 'trumpet', 'trunk', 'tube', 'tulip',
  'tundra', 'tunnel', 'turban', 'turbine', 'turkey', 'turnip', 'turret', 'turtle',
  'tusk', 'tuxedo', 'tweezers', 'twig', 'typhoon', 'ukulele', 'umbrella', 'unicorn',
  'vacuum', 'valley', 'vampire', 'vanilla', 'vase', 'vault', 'veil', 'velvet',
  'vest', 'viking', 'village', 'vine', 'violin', 'viper', 'volcano', 'vulture',
  'waffle', 'wagon', 'waiter', 'wall', 'walnut', 'walrus', 'wand', 'wardrobe',
  'warrior', 'wasp', 'watch', 'waterfall', 'wave', 'wax', 'weasel', 'web',
  'whale', 'wharf', 'wheat', 'wheel', 'whirlpool', 'whisk', 'whistle', 'willow',
  'window', 'wing', 'wire', 'wizard', 'wolf', 'wombat', 'wood', 'wool',
  'workshop', 'worm', 'wreath', 'wrench', 'wrist', 'xylophone', 'yacht', 'yak',
  'yarn', 'yeti', 'yogurt', 'zebra', 'zeppelin', 'zipper', 'zoo', 'zucchini',
];
