// ===========================================================================
// words.js — bundled word list (static asset).
// An original set of common, concrete English nouns. Not copied from any
// commercial card deck. 25 distinct words are drawn at random per game.
// Stored lowercase; the UI renders them uppercase via CSS.
// ===========================================================================

export const WORD_LIST = [
  'anchor', 'angel', 'apple', 'arch', 'arrow', 'attic', 'avalanche', 'axe',
  'bacon', 'badge', 'bakery', 'balloon', 'bamboo', 'banana', 'bandit', 'barn',
  'basket', 'battery', 'beach', 'beacon', 'beard', 'beaver', 'bee', 'beetle',
  'bell', 'belt', 'bench', 'berry', 'bicycle', 'bishop', 'blade', 'blanket',
  'blizzard', 'block', 'board', 'boat', 'bolt', 'bone', 'bonfire', 'bonnet',
  'book', 'boot', 'bottle', 'boulder', 'bow', 'bowl', 'box', 'bracelet',
  'brain', 'branch', 'brick', 'bridge', 'broom', 'brush', 'bubble', 'bucket',
  'buffalo', 'bugle', 'bulb', 'bull', 'bunker', 'button', 'cabin', 'cable',
  'cactus', 'cage', 'cake', 'camel', 'camera', 'candle', 'canyon', 'cape',
  'captain', 'card', 'cargo', 'carpet', 'carrot', 'cart', 'castle', 'cat',
  'cave', 'cello', 'chain', 'chair', 'chalk', 'chapel', 'cheese', 'cherry',
  'chess', 'chimney', 'chip', 'circle', 'circus', 'clamp', 'cliff', 'cloak',
  'clock', 'cloud', 'clover', 'clown', 'coast', 'coat', 'cobra', 'coconut',
  'coil', 'coin', 'collar', 'comet', 'compass', 'cone', 'cookie', 'copper',
  'coral', 'cork', 'corn', 'cottage', 'cotton', 'couch', 'cougar', 'crab',
  'crane', 'crater', 'crayon', 'cricket', 'crown', 'crystal', 'cube', 'cup',
  'curtain', 'cushion', 'dagger', 'daisy', 'dam', 'dart', 'deer', 'desert',
  'desk', 'diamond', 'dice', 'dinosaur', 'dock', 'doctor', 'dolphin', 'domino',
  'donkey', 'door', 'dragon', 'drum', 'duck', 'dune', 'eagle', 'ear',
  'earth', 'easel', 'egg', 'elbow', 'engine', 'envelope', 'fan', 'fang',
  'feather', 'fence', 'fern', 'ferry', 'fiddle', 'field', 'fig', 'finger',
  'fire', 'fish', 'flag', 'flame', 'flask', 'fleet', 'flood', 'flour',
  'flower', 'flute', 'fog', 'forest', 'fork', 'fort', 'fountain', 'fox',
  'frame', 'freckle', 'frog', 'frost', 'furnace', 'galaxy', 'garden', 'garlic',
  'gate', 'gear', 'ghost', 'giant', 'glacier', 'glass', 'glove', 'glue',
  'goat', 'goblin', 'gold', 'goose', 'gorilla', 'grape', 'grass', 'grave',
  'gravel', 'grill', 'guitar', 'gull', 'hammer', 'hammock', 'hamster', 'hand',
  'harbor', 'harp', 'hat', 'hawk', 'hay', 'heart', 'hedge', 'helmet',
  'hill', 'hive', 'hook', 'hoof', 'horn', 'horse', 'hose', 'hotel',
  'house', 'hut', 'igloo', 'ink', 'iron', 'island', 'ivory', 'jacket',
  'jaguar', 'jar', 'jelly', 'jet', 'jewel', 'jungle', 'kangaroo', 'kayak',
  'kettle', 'key', 'kingdom', 'kite', 'kitten', 'knee', 'knight', 'knot',
  'ladder', 'lake', 'lamp', 'lance', 'lantern', 'lava', 'leaf', 'leather',
  'leg', 'lemon', 'lens', 'leopard', 'letter', 'lighthouse', 'lily', 'lime',
  'lion', 'lizard', 'lobster', 'lock', 'log', 'lotus', 'magnet', 'mammoth',
  'mango', 'mansion', 'map', 'maple', 'marble', 'mask', 'mast', 'meadow',
  'medal', 'melon', 'mermaid', 'meteor', 'microscope', 'milk', 'mill', 'mirror',
  'mitten', 'moat', 'mole', 'monk', 'monkey', 'moon', 'moose', 'moss',
  'moth', 'mountain', 'mouse', 'mushroom', 'nail', 'napkin', 'needle', 'nest',
  'net', 'newt', 'noodle', 'nose', 'note', 'oak', 'oar', 'ocean',
  'octopus', 'olive', 'onion', 'orbit', 'orchard', 'organ', 'otter', 'oven',
  'owl', 'oyster', 'paddle', 'palace', 'palm', 'panda', 'pansy', 'panther',
  'paper', 'parachute', 'parrot', 'pasta', 'paw', 'pawn', 'peach', 'peacock',
  'pear', 'pearl', 'pebble', 'pelican', 'pencil', 'penguin', 'pepper', 'piano',
  'pickle', 'pier', 'pigeon', 'pillar', 'pillow', 'pine', 'pipe', 'pirate',
  'pistol', 'planet', 'plank', 'plate', 'plum', 'pocket', 'pond', 'pony',
  'porch', 'potato', 'pottery', 'pretzel', 'prism', 'puddle', 'pump', 'pumpkin',
  'puppet', 'puppy', 'pyramid', 'quail', 'quartz', 'queen', 'quill', 'quilt',
  'rabbit', 'raccoon', 'radish', 'raft', 'rail', 'rain', 'rake', 'ram',
  'ranch', 'raven', 'razor', 'reef', 'rhino', 'ribbon', 'rice', 'ring',
  'river', 'road', 'robe', 'robin', 'robot', 'rocket', 'rope', 'rose',
  'ruby', 'rug', 'ruler', 'sable', 'saddle', 'sail', 'salt', 'sand',
  'sandal', 'sapphire', 'satellite', 'saw', 'scale', 'scarf', 'school', 'scissors',
  'scooter', 'scorpion', 'screw', 'seal', 'seed', 'shark', 'shed', 'shell',
  'shield', 'ship', 'shirt', 'shoe', 'shovel', 'shrimp', 'sieve', 'silk',
  'silo', 'silver', 'sink', 'skate', 'skull', 'sky', 'sled', 'sloth',
  'snail', 'snake', 'snow', 'soap', 'sock', 'sofa', 'soldier', 'spade',
  'sparrow', 'spear', 'spider', 'spike', 'spinach', 'sponge', 'spoon', 'spring',
  'sprout', 'spruce', 'square', 'squid', 'squirrel', 'stable', 'stadium', 'stage',
  'stairs', 'stamp', 'star', 'statue', 'steam', 'steel', 'stem', 'stick',
  'stone', 'stool', 'storm', 'stove', 'straw', 'stream', 'street', 'string',
  'submarine', 'sugar', 'suitcase', 'summit', 'sun', 'swamp', 'swan', 'sword',
  'table', 'tail', 'tank', 'teapot', 'temple', 'tent', 'thimble', 'thorn',
  'thread', 'throne', 'thunder', 'tiger', 'tile', 'toast', 'tomato', 'tooth',
  'torch', 'tornado', 'tower', 'track', 'tractor', 'train', 'trap', 'tray',
  'treasure', 'tree', 'triangle', 'trophy', 'truck', 'trumpet', 'trunk', 'tube',
  'tulip', 'tunnel', 'turtle', 'tusk', 'umbrella', 'unicorn', 'valley', 'vase',
  'vault', 'velvet', 'vine', 'violin', 'volcano', 'vulture', 'waffle', 'wagon',
  'wall', 'walnut', 'walrus', 'wand', 'wasp', 'watch', 'waterfall', 'wave',
  'wax', 'web', 'whale', 'wheat', 'wheel', 'whistle', 'willow', 'window',
  'wing', 'wizard', 'wolf', 'wood', 'wool', 'worm', 'wreath', 'wrench',
  'yacht', 'yarn', 'zebra', 'zipper',
];
